mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat'
mod 'puppetlabs-translate'

mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.9.0'
#mod 'puppetlabs-apt', '7.3.0'
#mod 'puppetlabs-powershell', '3.0.0'
#mod 'puppetlabs-pwshlib', '0.3.0'
#mod 'puppetlabs-reboot', '2.3.0'
